mode = "get_full_spec"

[parameters]
injection_list_path = "/data.local/G22-00018_00203/results/ntcap/injection/injection_list.txt"
base_path = "/data.local/G22-00018_00203/results/ntcap/injection"
max_workers = "10"
frameID_offset = "20"
frameID_range = "50"
