# This is the path setting file

[paths]
luster_hostname = "****"
luster_username = "****"
luster_keyfilename = "****"
default_path_ntcap_iq = "***"
default_path_luster_iq = "***"
default_path_ntcap_sc = "***"
default_path_luster_sc = "***"